export const INICIAR_SESION = 'INICIAR_SESION'
export const INICIAR_SESION_EXITO = 'INICIAR_SESION_EXITO'
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR'

export const CONSULTAR_HOTELES = 'CONSULTAR_HOTELES'
export const CONSULTAR_HOTELES_EXITO = 'CONSULTAR_HOTELES_EXITO'
export const CONSULTAR_HOTELES_ERROR = 'CONSULTAR_HOTELES_ERROR'